version: "3"
services:
  app:
    image: mtd
    ports:
      - "8080:8080"
    volumes:
      - .:/root/project
    command: "sh -c 'swift package clean && swift build && swift test && .build-ubuntu/release/mtd'"
    working_dir: "/root/project"  