app:
  image: ibmcom/swift-ubuntu:3.1.1
  ports:
    - "8080:8080"
  volumes:
    - .:/root/mtd
  command: bash -c "cd /root/mtd && swift package clean && swift build && swift test && ./.build/debug/mtd"